# Generated by Django 5.2.4 on 2026-02-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0021_subjectresource_drive_folder_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectresource',
            name='solution_file_id',
            field=models.CharField(blank=True, help_text='Google Drive File ID for Solution', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subjectresource',
            name='solution_url',
            field=models.URLField(blank=True, help_text='URL for the solution file', max_length=500, null=True),
        ),
    ]
